<?php

namespace App\Service;

use App\Helpers\FileUploadHelper;
use App\Helpers\ResponseHelper;
use App\Models\RMImage;
use App\Models\RMPurchasingTransaction;
use App\Models\RMStockMovement;
use App\Models\RawMaterial;
use App\Validations\RMValidation;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\ValidationException;

class RawMaterialService
{
    protected RMValidation $rmValidation;

    public function __construct(RMValidation $rmValidation)
    {
        $this->rmValidation = $rmValidation;
    }

    public function createRawMaterial(Request $request)
    {
        try {
            // Default status for newly purchased raw material
            if (!$request->filled('status')) {
                $request->merge(['status' => 'IN_STOCK']);
            }

            // Default transaction date (if client doesn't send it)
            if (!$request->filled('transaction_date')) {
                $request->merge(['transaction_date' => now()->toDateString()]);
            }

            // Validate all required inputs up-front and return ALL errors at once.
            $mergeErrors = function (array $base, array $incoming): array {
                foreach ($incoming as $field => $messages) {
                    $base[$field] = array_values(array_unique(array_merge($base[$field] ?? [], $messages)));
                }
                return $base;
            };

            $errors = [];

            $rawMaterialRules = $this->rmValidation->CreateRMValidation($request);
            $rawMaterialValidator = Validator::make($request->all(), $rawMaterialRules);
            if ($rawMaterialValidator->fails()) {
                $errors = $mergeErrors($errors, $rawMaterialValidator->errors()->toArray());
            }

            // Purchasing: raw_material_id is generated by the service, so don't validate it here.
            $purchasingRules = $this->rmValidation->CreateRMPurchasingTransactionValidation($request);
            unset($purchasingRules['raw_material_id']);
            $purchasingValidator = Validator::make($request->all(), $purchasingRules);
            if ($purchasingValidator->fails()) {
                $errors = $mergeErrors($errors, $purchasingValidator->errors()->toArray());
            }

            // Images: raw_material_id is generated by the service, so don't validate it here.
            $imageRules = $this->rmValidation->CreateRMImageValidation($request);
            unset($imageRules['raw_material_id']);
            $imageValidator = Validator::make($request->all(), $imageRules);
            if ($imageValidator->fails()) {
                $errors = $mergeErrors($errors, $imageValidator->errors()->toArray());
            }

            if (!empty($errors)) {
                return ResponseHelper::validation($errors, 'Validation Error');
            }

            return DB::transaction(function () use ($request) {
                /**
                 * 1) Raw Material main data
                 */
                $rawMaterialRules = $this->rmValidation->CreateRMValidation($request);
                Validator::make($request->all(), $rawMaterialRules)->validate();

                $rawMaterial = RawMaterial::create([
                    'material_name' => $request->input('material_name'),
                    'material_sku_code' => $request->input('material_sku_code'),
                    'barcode' => $request->input('barcode'),
                    'minimum_quantity_stock_level' => $request->input('minimum_quantity_stock_level'),
                    'expiry_date' => $request->input('expiry_date'),
                    'status' => $request->input('status', 'IN_STOCK'),
                    'description' => $request->input('description'),
                    'raw_material_category_id' => $request->input('raw_material_category_id'),
                    'uom_id' => $request->input('uom_id'),
                    'supplier_id' => $request->input('supplier_id'), // nullable in main table
                    'warehouse_id' => $request->input('warehouse_id'),
                ]);

                /**
                 * 2) Purchasing transaction
                 * - raw_material_id from above
                 * - supplier_id from request (required for purchasing)
                 * - compute totals and KHR fields from USD + exchange rate (handled in validation helper)
                 * - total_value should be unit_price * quantity (handled by CurrencyPricingHelper)
                 */
                $request->merge([
                    'raw_material_id' => $rawMaterial->id,
                ]);

                $purchasingRules = $this->rmValidation->CreateRMPurchasingTransactionValidation($request);
                Validator::make($request->all(), $purchasingRules)->validate();

                $purchase = RMPurchasingTransaction::create([
                    'raw_material_id' => $rawMaterial->id,
                    'supplier_id' => $request->input('supplier_id'),
                    'quantity' => $request->input('quantity'),
                    'transaction_date' => $request->input('transaction_date'),

                    'unit_price_in_usd' => $request->input('unit_price_in_usd'),
                    'total_value_in_usd' => $request->input('total_value_in_usd'),

                    'exchange_rate_from_usd_to_riel' => $request->input('exchange_rate_from_usd_to_riel'),
                    'unit_price_in_riel' => $request->input('unit_price_in_riel'),
                    'total_value_in_riel' => $request->input('total_value_in_riel'),
                    'exchange_rate_from_riel_to_usd' => $request->input('exchange_rate_from_riel_to_usd'),
                ]);

                /**
                 * 3) Stock movement (initial IN, PURCHASE, now)
                 */
                $request->merge([
                    'raw_material_id' => $rawMaterial->id,
                    'direction' => 'IN',
                    'movement_type' => 'PURCHASE',
                    'movement_date' => now()->toDateTimeString(),
                    // quantity comes from purchasing transaction
                    'quantity' => $request->input('quantity'),
                ]);

                $stockMovementRules = $this->rmValidation->CreateRMStockMovementValidation($request);
                Validator::make($request->all(), $stockMovementRules)->validate();

                $movement = RMStockMovement::create([
                    'raw_material_id' => $rawMaterial->id,
                    'quantity' => $request->input('quantity'),
                    'direction' => 'IN',
                    'movement_type' => 'PURCHASE',
                    'movement_date' => $request->input('movement_date'),
                ]);

                /**
                 * 4) Raw material images
                 * - max 4 images
                 * - <= 2MB each
                 * - support either:
                 *    - image (single)
                 *    - images[] (multiple)
                 */
                $files = [];

                if ($request->hasFile('images')) {
                    $files = $request->file('images');
                } elseif ($request->hasFile('image')) {
                    $files = [$request->file('image')];
                }

                if (!empty($files)) {
                    // Validate images (supports image or images[])
                    $request->merge(['raw_material_id' => $rawMaterial->id]);
                    $imageRules = $this->rmValidation->CreateRMImageValidation($request);
                    Validator::make($request->all(), $imageRules)->validate();

                    foreach ($files as $file) {
                        $imageUrl = FileUploadHelper::uploadSingle($file, 'raw-materials', null);
                        RMImage::create([
                            'raw_material_id' => $rawMaterial->id,
                            'image' => $imageUrl,
                        ]);
                    }
                }

                $data = [
                    'raw_material' => $rawMaterial->fresh(),
                    'purchasing_transaction' => $purchase,
                    'stock_movement' => $movement,
                ];

                return ResponseHelper::success($data, 'Raw material created successfully', 201);
            });
        } catch (ValidationException $e) {
            return ResponseHelper::validation($e->errors(), 'Validation Error');
        } catch (\Exception $e) {
            return ResponseHelper::error($e->getMessage(), 500);
        }
    }
}






// I have updated some of my database fields as you can see in this validation fields:

// <?php 


// namespace App\Validations;


// use App\Helpers\GenerateUniqueSKU;
// use App\Helpers\CurrencyPricingHelper;
// use App\Models\RawMaterial;
// use App\Models\RawMaterialCategory;
// use Illuminate\Http\Request;

// class RMValidation {


//     // Handle the validation for creating a Raw Material
//     public function CreateRMValidation (Request $request): array
//     {
//         $rm = new RawMaterial();

//         $relations = [];
//         $format = '{prefix}-{random}';

//         // Use the category chosen by the user (raw_material_category_id)
//         if ($request->filled('raw_material_category_id')) {
//             $cat = RawMaterialCategory::find($request->input('raw_material_category_id'));

//             if ($cat) {
//                 $rm->rm_category()->associate($cat);
//                 $relations = ['cat' => 'rm_category.category_name'];
//                 $format = '{prefix}-{cat}-{random}';
//             }
//         }

//         if (!$request->filled('material_sku_code')) {
//             $request->merge([
//                 'material_sku_code' => GenerateUniqueSKU::generate(
//                     model: $rm,
//                     field: 'material_sku_code',
//                     randomLength: 6,
//                     prefix: 'RM',
//                     relations: $relations,
//                     format: $format
//                 )
//             ]);
//         }

//         return [
//             'material_name' => 'required|string|max:255',
//             'material_sku_code' => 'required|string|unique:raw_materials,material_sku_code|max:255',
//             'barcode' => 'nullable|string|max:255',
//             'minimum_quantity_stock_level' => 'required|numeric|min:0',
//             'expiry_date' => 'nullable|date',
//             'status' => 'required|in:IN_STOCK,OUT_OF_STOCK,LOW_STOCK,EXPIRED',
//             'description' => 'nullable|string',
//             'raw_material_category_id' => 'required|exists:raw_material_categories,id',
//             'uom_id' => 'required|exists:uoms,id',
//             'supplier_id' => 'nullable|exists:suppliers,id',
//             'warehouse_id' => 'required|exists:warehouses,id',
//         ];
//     }


//     public function CreateRMPurchasingTransactionValidation (Request $request): array
//     {
//         CurrencyPricingHelper::fillRMPurchasingCurrencyFields($request);

//         return [
//             'raw_material_id' => 'required|exists:raw_materials,id',
//             'supplier_id' => 'required|exists:suppliers,id',
//             'quantity' => 'required|numeric|min:0',
//             'transaction_date' => 'required|date',
//             'unit_price_in_usd' => 'required|numeric|min:0',
//             'total_value_in_usd' => 'required|numeric|min:0',
//             'exchange_rate_from_usd_to_riel' => 'required|numeric|min:0',
//             'unit_price_in_riel' => 'required|numeric|min:0',
//             'total_value_in_riel' => 'required|numeric|min:0',
//             'exchange_rate_from_riel_to_usd' => 'required|numeric|min:0',
//         ];
//     }


//     public function CreateRMStockMovementValidation (Request $request): array
//     {
//         return [
//             'raw_material_id' => 'required|exists:raw_materials,id',
//             'quantity' => 'required|numeric|min:0',
//             'direction' => 'required|in:IN,OUT',
//             'movement_type' => (function () use ($request) {
//                 if (!$request->filled('movement_type')) {
//                     $request->merge(['movement_type' => 'PURCHASE']);
//                 }
//                 return 'required|in:PURCHASE,RE_ORDER,SALE,PRODUCTION_SCRAP,PRODUCTION_RECEIPT,ADJUSTMENT_IN,ADJUSTMENT_OUT';
//             })(),
//             'movement_date' => 'required|date',
//         ];
//     }

//     public function CreateRMImageValidation (Request $request): array
//     {
//         return [
//             'raw_material_id' => 'required|exists:raw_materials,id',
//             'image' => 'required|image|max:2048',
//         ];
//     }
// }



// Please write me a raw material service to implement the create function of raw material. This is my flow and please implement as what I suggest:

// 1. Raw Material main data table:
//             'material_name' => 'required|string|max:255',
//             'material_sku_code' => 'required|string|unique:raw_materials,material_sku_code|max:255',
//             'barcode' => 'nullable|string|max:255',
//             'minimum_quantity_stock_level' => 'required|numeric|min:0',
//             'expiry_date' => 'nullable|date',
//             'status' => 'required|in:IN_STOCK,OUT_OF_STOCK,LOW_STOCK,EXPIRED',
//             'description' => 'nullable|string',
//             'raw_material_category_id' => 'required|exists:raw_material_categories,id',
//             'uom_id' => 'required|exists:uoms,id',
//             'supplier_id' => 'nullable|exists:suppliers,id',
//             'warehouse_id' => 'required|exists:warehouses,id',

//             allow user to input the following information as needed. The default value fo the status is IN_STOCK since the very begining of the raw mateirial created is PURCHASE.


//            2. Raw Material Purchasing Transaction:
//            - Get the raw material id from the above feature
//            - Get supplier id from the above feature as well (This will useful for profit/loss that company spent with supplier).
//            - Use the currency helper to calculate pricing of this purchasing. Please allow user to input the usd currency with exchange from usd to khmer to calculate the khmer pricing. Please be noted that, the total value should be come from unit pricing multiple by quantity.


//            3. Stock Movement:
//            - get the raw material from above feature
//            - get quantity from purchasing transaction as an initail stock movement
//            - the direction should be IN since it's is the stock increment
//            - movement type should be PURCHASE in create function by default.
//            - please added movement date as now.

//            4. Raw Material Image: Please use FileUploadHelper to implement the upload function. The image should be only 4 at max and below 2MB.